name: to_do_app
description: "A modern Flutter To-Do application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
